### ISSUE TITLE
Be able to add targets with re-labeling

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DMS#9]
Some exporters need to use re-labeling for managing the targets, like blackbox exporter:

```
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```
We need to try to figure it out how to add this functionality to be able to support it.
